# 2024-12-05
# https://github.com/Moli-X/Tool/blob/X/.github/workflows/Fork.yml

name: Build & Update

on:
  workflow_dispatch:
  schedule:
    - cron: "30 * * * *"

permissions:
  actions: write  
  contents: write  



jobs:
  BuildUpdateRepository:
    runs-on: ubuntu-latest
    env:
      TZ: 'Asia/Shanghai'
    
    steps: 
    - name: 验证目标存储库
      uses: actions/checkout@v4.2.2
      with:
        repository: sooyaaabo/Kelee-Loon
        path: Kelee-Loon


###### 控制开关

    # 环境判断
    - name: 设置环境变量
      id: set-env
      run: |

        # 调试模式是否开启
        Debug=false  
        echo "Debug状态为：$Debug"

        if [ "$Debug" = true ]; then
          # 如果 Debug 模式开启，所有开关关闭
          echo "LOON_SWITCH=false" >> $GITHUB_ENV
          echo "CLASH_SWITCH=false" >> $GITHUB_ENV
          echo "QUANTUMULTX_SWITCH=false" >> $GITHUB_ENV
          echo "SURGE_SWITCH=false" >> $GITHUB_ENV
          echo "EGERN_SWITCH=false" >> $GITHUB_ENV
          echo "SHADOWROCKET_SWITCH=false" >> $GITHUB_ENV
          echo "STASH_SWITCH=false" >> $GITHUB_ENV
          echo "Debug 模式开启，所有开关关闭"
        else
          # 正常模式，设置相应的开关
          echo "LOON_SWITCH=true" >> $GITHUB_ENV
          echo "CLASH_SWITCH=true" >> $GITHUB_ENV
          echo "QUANTUMULTX_SWITCH=true" >> $GITHUB_ENV
          echo "SURGE_SWITCH=true" >> $GITHUB_ENV
          echo "EGERN_SWITCH=true" >> $GITHUB_ENV
          echo "SHADOWROCKET_SWITCH=true" >> $GITHUB_ENV
          echo "STASH_SWITCH=true" >> $GITHUB_ENV
          echo "Debug 模式关闭，所有正常运行"
        fi


###### Loon
    - name: Loon
      if: env.LOON_SWITCH == 'false'  # 添加开关条件
      run: |
        for file in Kelee-Loon/Rules/*.list; do
          if [ -f "$file" ]; then
            sed -i -e '/^PROCESS-NAME/d' "$file"
            file_names=$(basename "$file" .list)
            line_count=$(wc -l < "$file")
            awk -v fname="$file_names" 'NR==1 {print "# 规则名称: " fname} {print}' "$file" > tmpfile && mv tmpfile "$file"
            awk -v count="$line_count" 'NR==2 {print "# 规则统计: " count} {print}' "$file" > tmpfile && mv tmpfile "$file"
            sed -i '2a\\' "$file"
          else
            echo "$file not found."
          fi
        done


    - name: 批量复刻LOON模块
      if: env.LOON_SWITCH == 'true'  # 添加开关条件
      run: |
        mkdir -p Kelee-Loon/Plugin

        
        # 定义插件及其原链接
        declare -A plugins=(
            [BlockAdvertisers]="https://kelee.one/Tool/Loon/Plugin/BlockAdvertisers.plugin"
            [Remove_ads_by_keli]="https://kelee.one/Tool/Loon/Plugin/Remove_ads_by_keli.plugin"
            [Cainiao_remove_ads]="https://kelee.one/Tool/Loon/Plugin/Cainiao_remove_ads.plugin"
            [Himalaya_remove_ads]="https://kelee.one/Tool/Loon/Plugin/Himalaya_remove_ads.plugin"
            [Tieba_remove_ads]="https://kelee.one/Tool/Loon/Plugin/Tieba_remove_ads.plugin"
            [YouTube_remove_ads]="https://kelee.one/Tool/Loon/Plugin/YouTube_remove_ads.plugin"
            [Weibo_remove_ads]="https://kelee.one/Tool/Loon/Plugin/Weibo_remove_ads.plugin"
            [Bilibili_remove_ads]="https://kelee.one/Tool/Loon/Plugin/Bilibili_remove_ads.plugin"
            [Weibo_intl_remove_ads]="https://kelee.one/Tool/Loon/Plugin/Weibo_intl_remove_ads.plugin"
            [Baidu_input_method_remove_ads]="https://kelee.one/Tool/Loon/Plugin/Baidu_input_method_remove_ads.plugin"
            [Zhihu_remove_ads]="https://kelee.one/Tool/Loon/Plugin/Zhihu_remove_ads.plugin"
            [NeteaseCloudMusic_remove_ads]="https://kelee.one/Tool/Loon/Plugin/NeteaseCloudMusic_remove_ads.plugin"
            [CoolApk_remove_ads]="https://kelee.one/Tool/Loon/Plugin/CoolApk_remove_ads.plugin"
            [smzdm_remove_ads]="https://kelee.one/Tool/Loon/Plugin/smzdm_remove_ads.plugin"
            [RedPaper_remove_ads]="https://kelee.one/Tool/Loon/Plugin/RedPaper_remove_ads.plugin"
            [Weixin_Official_Accounts_remove_ads]="https://kelee.one/Tool/Loon/Plugin/Weixin_Official_Accounts_remove_ads.plugin"
            [QQMusic_remove_ads]="https://kelee.one/Tool/Loon/Plugin/QQMusic_remove_ads.plugin"
            [Daily_remove_ads]="https://kelee.one/Tool/Loon/Plugin/Daily_remove_ads.plugin"
            [IThome_remove_ads]="https://kelee.one/Tool/Loon/Plugin/IThome_remove_ads.plugin"
            [BaiduSearchWebpage_remove_ads]="https://kelee.one/Tool/Loon/Plugin/BaiduSearchWebpage_remove_ads.plugin"
            [BaiduNetDisk_remove_ads]="https://kelee.one/Tool/Loon/Plugin/BaiduNetDisk_remove_ads.plugin"
            [TubeMax_remove_ads]="https://kelee.one/Tool/Loon/Plugin/TubeMax_remove_ads.plugin"
            [Amap_remove_ads]="https://kelee.one/Tool/Loon/Plugin/Amap_remove_ads.plugin"
            [WexinMiniPrograms_Remove_ads]="https://kelee.one/Tool/Loon/Plugin/WexinMiniPrograms_Remove_ads.plugin"
            [QiDian_remove_ads]="https://kelee.one/Tool/Loon/Plugin/QiDian_remove_ads.plugin"
            [AliYunDrive_remove_ads]="https://kelee.one/Tool/Loon/Plugin/AliYunDrive_remove_ads.plugin"
            [iQiYi_Video_remove_ads]="https://kelee.one/Tool/Loon/Plugin/iQiYi_Video_remove_ads.plugin"
            [DragonRead_remove_ads]="https://kelee.one/Tool/Loon/Plugin/DragonRead_remove_ads.plugin"
            [YouKu_Video_remove_ads]="https://kelee.one/Tool/Loon/Plugin/YouKu_Video_remove_ads.plugin"
            [BabyTree_remove_ads]="https://kelee.one/Tool/Loon/Plugin/BabyTree_remove_ads.plugin"
            [Tencent_Video_remove_ads]="https://kelee.one/Tool/Loon/Plugin/Tencent_Video_remove_ads.plugin"
            [CaixinMedia_remove_ads]="https://kelee.one/Tool/Loon/Plugin/CaixinMedia_remove_ads.plugin"
            [Mango_Viedo_remove_ads]="https://kelee.one/Tool/Loon/Plugin/Mango_Viedo_remove_ads.plugin"
            [Umetrip_remove_ads]="https://kelee.one/Tool/Loon/Plugin/Umetrip_remove_ads.plugin"
            [JD_remove_ads]="https://kelee.one/Tool/Loon/Plugin/JD_remove_ads.plugin"
            [PiPiXia_remove_ads]="https://kelee.one/Tool/Loon/Plugin/PiPiXia_remove_ads.plugin"
            [Taobao_remove_ads]="https://kelee.one/Tool/Loon/Plugin/Taobao_remove_ads.plugin"
            [NeteaseNews_remove_ads]="https://kelee.one/Tool/Loon/Plugin/NeteaseNews_remove_ads.plugin"
            [12306_remove_ads]="https://kelee.one/Tool/Loon/Plugin/12306_remove_ads.plugin"
            [Reddit_remove_ads]="https://kelee.one/Tool/Loon/Plugin/Reddit_remove_ads.plugin"
            [Soul_remove_ads]="https://kelee.one/Tool/Loon/Plugin/Soul_remove_ads.plugin"
            [QQKSong_remove_ads]="https://kelee.one/Tool/Loon/Plugin/QQKSong_remove_ads.plugin"
            [mobileClouds_remove_ads]="https://kelee.one/Tool/Loon/Plugin/mobileClouds_remove_ads.plugin"
            [PICC_Insurance_remove_ads]="https://kelee.one/Tool/Loon/Plugin/PICC_Insurance_remove_ads.plugin"
            [Spotify_remove_ads]="https://kelee.one/Tool/Loon/Plugin/Spotify_remove_ads.plugin"
            [SevenCat_remove_ads]="https://kelee.one/Tool/Loon/Plugin/SevenCat_remove_ads.plugin"
            [HUPU_remove_ads]="https://kelee.one/Tool/Loon/Plugin/HUPU_remove_ads.plugin"
            [GaoDing_remove_ads]="https://kelee.one/Tool/Loon/Plugin/GaoDing_remove_ads.plugin"
            [PuPuMall_remove_ads]="https://kelee.one/Tool/Loon/Plugin/PuPuMall_remove_ads.plugin"
            [DiDi_remove_ads]="https://kelee.one/Tool/Loon/Plugin/DiDi_remove_ads.plugin"
            [Aiinquiry_remove_ads]="https://kelee.one/Tool/Loon/Plugin/Aiinquiry_remove_ads.plugin"
            [QiXinBao_remove_ads]="https://kelee.one/Tool/Loon/Plugin/QiXinBao_remove_ads.plugin"
            [ZhuanZhuan_remove_ads]="https://kelee.one/Tool/Loon/Plugin/ZhuanZhuan_remove_ads.plugin"
            [RiskBird_remove_ads]="https://kelee.one/Tool/Loon/Plugin/RiskBird_remove_ads.plugin"
            [iMaiCai_remove_ads]="https://kelee.one/Tool/Loon/Plugin/iMaiCai_remove_ads.plugin"
            [ZuiYou_remove_ads]="https://kelee.one/Tool/Loon/Plugin/ZuiYou_remove_ads.plugin"
            [MailMaster_remove_ads]="https://kelee.one/Tool/Loon/Plugin/MailMaster_remove_ads.plugin"
            [MiaoRead_remove_ads]="https://kelee.one/Tool/Loon/Plugin/MiaoRead_remove_ads.plugin"
            [SafetyHome_remove_ads]="https://kelee.one/Tool/Loon/Plugin/SafetyHome_remove_ads.plugin"
            [360SmartCamera_remove_ads]="https://kelee.one/Tool/Loon/Plugin/360SmartCamera_remove_ads.plugin"
            [VideoGo_remove_ads]="https://kelee.one/Tool/Loon/Plugin/VideoGo_remove_ads.plugin"
            [FlyerTea_remove_ads]="https://kelee.one/Tool/Loon/Plugin/FlyerTea_remove_ads.plugin"
            [ShouYinTongMerchant_remove_ads]="https://kelee.one/Tool/Loon/Plugin/ShouYinTongMerchant_remove_ads.plugin"
            [FenBi_remove_ads]="https://kelee.one/Tool/Loon/Plugin/FenBi_remove_ads.plugin"
            [TV_Assistant_remove_ads]="https://kelee.one/Tool/Loon/Plugin/TV_Assistant_remove_ads.plugin"
            [XiaoHeiHe_remove_ads]="https://kelee.one/Tool/Loon/Plugin/XiaoHeiHe_remove_ads.plugin"
            [Snowball_remove_ads]="https://kelee.one/Tool/Loon/Plugin/Snowball_remove_ads.plugin"
            [KingdeeMyMoney_remove_ads]="https://kelee.one/Tool/Loon/Plugin/KingdeeMyMoney_remove_ads.plugin"
            [XunLei_remove_ads]="https://kelee.one/Tool/Loon/Plugin/XunLei_remove_ads.plugin"
            [ShuQiCenterReader_remove_ads]="https://kelee.one/Tool/Loon/Plugin/ShuQiCenterReader_remove_ads.plugin"
            [QuarkBrowser_remove_ads]="https://kelee.one/Tool/Loon/Plugin/QuarkBrowser_remove_ads.plugin"
            [JiaXiaoDrive_remove_ads]="https://kelee.one/Tool/Loon/Plugin/JiaXiaoDrive_remove_ads.plugin"
            [JiaKaoBaoDian_remove_ads]="https://kelee.one/Tool/Loon/Plugin/JiaKaoBaoDian_remove_ads.plugin"
            [DuiTang_remove_ads]="https://kelee.one/Tool/Loon/Plugin/DuiTang_remove_ads.plugin"
            [AutoHome_remove_ads]="https://kelee.one/Tool/Loon/Plugin/AutoHome_remove_ads.plugin"
            [KuGou_remove_ads]="https://kelee.one/Tool/Loon/Plugin/KuGou_remove_ads.plugin"
            [Kuwo_remove_ads]="https://kelee.one/Tool/Loon/Plugin/Kuwo_remove_ads.plugin"
            [DubbingShow_remove_ads]="https://kelee.one/Tool/Loon/Plugin/DubbingShow_remove_ads.plugin"
            [MKZ_remove_ads]="https://kelee.one/Tool/Loon/Plugin/MKZ_remove_ads.plugin"
            [KuaiKanComic_remove_ads]="https://kelee.one/Tool/Loon/Plugin/KuaiKanComic_remove_ads.plugin"
            [BiliComic_remove_ads]="https://kelee.one/Tool/Loon/Plugin/BiliComic_remove_ads.plugin"
            [XFuse_remove_ads]="https://kelee.one/Tool/Loon/Plugin/XFuse_remove_ads.plugin"
            [ColorfulClouds_remove_ads]="https://kelee.one/Tool/Loon/Plugin/ColorfulClouds_remove_ads.plugin"
            [Uki_remove_ads]="https://kelee.one/Tool/Loon/Plugin/Uki_remove_ads.plugin"
            [Douyu_remove_ads]="https://kelee.one/Tool/Loon/Plugin/Douyu_remove_ads.plugin"
            [GuideRank_remove_ads]="https://kelee.one/Tool/Loon/Plugin/GuideRank_remove_ads.plugin"
            [FleaMarket_remove_ads]="https://kelee.one/Tool/Loon/Plugin/FleaMarket_remove_ads.plugin"
            [PinDuoDuo_remove_ads]="https://kelee.one/Tool/Loon/Plugin/PinDuoDuo_remove_ads.plugin"
            [CatEarFM_remove_ads]="https://kelee.one/Tool/Loon/Plugin/CatEarFM_remove_ads.plugin"
            [XiaoCan_remove_ads]="https://kelee.one/Tool/Loon/Plugin/XiaoCan_remove_ads.plugin"
            [BooHee_remove_ads]="https://kelee.one/Tool/Loon/Plugin/BooHee_remove_ads.plugin"
            [MaiMai_remove_ads]="https://kelee.one/Tool/Loon/Plugin/MaiMai_remove_ads.plugin"
            [YoudaoDict_remove_ads]="https://kelee.one/Tool/Loon/Plugin/YoudaoDict_remove_ads.plugin"
            [MeiTu_remove_ads]="https://kelee.one/Tool/Loon/Plugin/MeiTu_remove_ads.plugin"
            [555DY_remove_ads]="https://kelee.one/Tool/Loon/Plugin/555DY_remove_ads.plugin"
            [SeasunJX3_remove_ads]="https://kelee.one/Tool/Loon/Plugin/SeasunJX3_remove_ads.plugin"
            [Keep_remove_ads]="https://kelee.one/Tool/Loon/Plugin/Keep_remove_ads.plugin"
            [123NetWorkDisk_remove_ads]="https://kelee.one/Tool/Loon/Plugin/123NetWorkDisk_remove_ads.plugin"
            [YoudaoTrans_remove_ads]="https://kelee.one/Tool/Loon/Plugin/YoudaoTrans_remove_ads.plugin"
            [MeituMYXJ_remove_ads]="https://kelee.one/Tool/Loon/Plugin/MeituMYXJ_remove_ads.plugin"
            [YY_Voice_remove_ads]="https://kelee.one/Tool/Loon/Plugin/YY_Voice_remove_ads.plugin"
            [SF-Express_remove_ads]="https://kelee.one/Tool/Loon/Plugin/SF-Express_remove_ads.plugin"
            [91160_remove_ads]="https://kelee.one/Tool/Loon/Plugin/91160_remove_ads.plugin"
            [NetEaseGodlike_remove_ads]="https://kelee.one/Tool/Loon/Plugin/NetEaseGodlike_remove_ads.plugin"
            [SodaMusic_remove_ads]="https://kelee.one/Tool/Loon/Plugin/SodaMusic_remove_ads.plugin"
            [KuaiDi100_remove_ads]="https://kelee.one/Tool/Loon/Plugin/KuaiDi100_remove_ads.plugin"
            [ChengFenMiao_remove_ads]="https://kelee.one/Tool/Loon/Plugin/ChengFenMiao_remove_ads.plugin"
            [FC_Box_remove_ads]="https://kelee.one/Tool/Loon/Plugin/FC_Box_remove_ads.plugin"
            [KGRing_remove_ads]="https://kelee.one/Tool/Loon/Plugin/KGRing_remove_ads.plugin"
            [ZongHeng_remove_ads]="https://kelee.one/Tool/Loon/Plugin/ZongHeng_remove_ads.plugin"
            [51Job_remove_ads]="https://kelee.one/Tool/Loon/Plugin/51Job_remove_ads.plugin"
            [MeetYou_remove_ads]="https://kelee.one/Tool/Loon/Plugin/MeetYou_remove_ads.plugin"
            [Yueyou_remove_ads]="https://kelee.one/Tool/Loon/Plugin/Yueyou_remove_ads.plugin"
            [MaFengWo_remove_ads]="https://kelee.one/Tool/Loon/Plugin/MaFengWo_remove_ads.plugin"
            [OraySunlogin_remove_ads]="https://kelee.one/Tool/Loon/Plugin/OraySunlogin_remove_ads.plugin"
            [BaiduPhoto_remove_ads]="https://kelee.one/Tool/Loon/Plugin/BaiduPhoto_remove_ads.plugin"
            [KuaiDuiZuoYe_remove_ads]="https://kelee.one/Tool/Loon/Plugin/KuaiDuiZuoYe_remove_ads.plugin"
            [EtouchEcalendar_remove_ads]="https://kelee.one/Tool/Loon/Plugin/EtouchEcalendar_remove_ads.plugin"
            [BitqiuPan_remove_ads]="https://kelee.one/Tool/Loon/Plugin/BitqiuPan_remove_ads.plugin"
            [MojiWeather_remove_ads]="https://kelee.one/Tool/Loon/Plugin/MojiWeather_remove_ads.plugin"
            [MeiShiJie_remove_ads]="https://kelee.one/Tool/Loon/Plugin/MeiShiJie_remove_ads.plugin"
            [XiaChuFang_remove_ads]="https://kelee.one/Tool/Loon/Plugin/XiaChuFang_remove_ads.plugin"
            [KwaiVideoeditor_remove_ads]="https://kelee.one/Tool/Loon/Plugin/KwaiVideoeditor_remove_ads.plugin"
            [LuckinCoffee_remove_ads]="https://kelee.one/Tool/Loon/Plugin/LuckinCoffee_remove_ads.plugin"
            [QtingFM_remove_ads]="https://kelee.one/Tool/Loon/Plugin/QtingFM_remove_ads.plugin"
            [UnionPay_remove_ads_with_ssl_unpinning]="https://kelee.one/Tool/Loon/Plugin/UnionPay_remove_ads_with_ssl_unpinning.plugin"
            [DouBan_remove_ads]="https://kelee.one/Tool/Loon/Plugin/DouBan_remove_ads.plugin"
            [BaiduMap_remove_ads]="https://kelee.one/Tool/Loon/Plugin/BaiduMap_remove_ads.plugin"
            [FC_Box_remove_ads]="https://kelee.one/Tool/Loon/Plugin/FC_Box_remove_ads.plugin"
            [ZhiLianZhaoPin_remove_ads]="https://kelee.one/Tool/Loon/Plugin/ZhiLianZhaoPin_remove_ads.plugin"
            [LoonGallery]="https://kelee.one/Tool/Loon/Plugin/LoonGallery.plugin"
            [Script-Hub]="https://kelee.one/Tool/Loon/Plugin/Script-Hub.plugin"
            [Sub-Store]="https://kelee.one/Tool/Loon/Plugin/Sub-Store.plugin"
            [Google]="https://kelee.one/Tool/Loon/Plugin/Google.plugin"
            [1.1.1.1]="https://kelee.one/Tool/Loon/Plugin/1.1.1.1.plugin"
            [BoxJs]="https://kelee.one/Tool/Loon/Plugin/BoxJs.plugin"
            [WARP_Node_Query]="https://kelee.one/Tool/Loon/Plugin/WARP_Node_Query.plugin"
            [JD_Price]="https://kelee.one/Tool/Loon/Plugin/JD_Price.plugin"
            [YouTubeSubtitlesTranslation]="https://kelee.one/Tool/Loon/Plugin/YouTubeSubtitlesTranslation.plugin"
            [Auto_Join_TF]="https://kelee.one/Tool/Loon/Plugin/Auto_Join_TF.plugin"
            [VVebo_repair]="https://kelee.one/Tool/Loon/Plugin/VVebo_repair.plugin"
            [TestFlightRegionUnlock]="https://kelee.one/Tool/Loon/Plugin/TestFlightRegionUnlock.plugin"
            [Switch_github_mirror]="https://kelee.one/Tool/Loon/Plugin/Switch_github_mirror.plugin"
            [Node_detection_tool]="https://kelee.one/Tool/Loon/Plugin/Node_detection_tool.plugin"
            [QQ_Redirect]="https://kelee.one/Tool/Loon/Plugin/QQ_Redirect.plugin"
            [Fileball_mount]="https://kelee.one/Tool/Loon/Plugin/Fileball_mount.plugin"
            [Block_HTTPDNS]="https://kelee.one/Tool/Loon/Plugin/Block_HTTPDNS.plugin"
            [Weixin_external_links_unlock]="https://kelee.one/Tool/Loon/Plugin/Weixin_external_links_unlock.plugin"
            [TikTok_redirectn]="https://kelee.one/Tool/Loon/Plugin/TikTok_redirect.plugin"
            [Spotify_lyrics_translation]="https://kelee.one/Tool/Loon/Plugin/Spotify_lyrics_translation.plugin"
            [NodeLinkCheck]="https://kelee.one/Tool/Loon/Plugin/NodeLinkCheck.Plugin"
            [QuickSearchn]="https://kelee.one/Tool/Loon/Plugin/QuickSearch.plugin"
            [UnnooQuan_remove_watermark]="https://kelee.one/Tool/Loon/Plugin/UnnooQuan_remove_watermark.plugin"
            [AppleWeatherEnhancer]="https://kelee.one/Tool/Loon/Plugin/AppleWeatherEnhancer.plugin"
            [BiliBiliDailyBonus]="https://raw.githubusercontent.com/ClydeTime/BiliBili/master/modules/BiliBiliDailyBonus.plugin"
            [WPS_checkin]="https://kelee.one/Tool/Loon/Plugin/WPS_checkin.plugin"
            [sxmd_sign]="https://raw.githubusercontent.com/bgvioletsky/ios_rule/main/Loon/plugin/sxmd_sign.plugin"
            [FollowRSS_checkin]="https://kelee.one/Tool/Loon/Plugin/FollowRSS_checkin.plugin"
        )
        
        # 下载插件并在文件中添加原链接
        for plugin_name in "${!plugins[@]}"; do
            url="${plugins[$plugin_name]}"
            curl -A "Surge iOS/3367" -L -o "Kelee-Loon/Plugin/${plugin_name}.plugin" "$url"
            
            # 将原链接添加到文件开头
           # echo "# 原链接 : $url" | cat - "Kelee-Loon/Plugin/$plugin_name.plugin" > temp && mv temp "Kelee-Loon/Plugin/$plugin_name.plugin"
            sed -i "1s|^|# 原链接 : $url\n|" "Kelee-Loon/Plugin/$plugin_name.plugin"  # 在文件开头添加原链接
        done

        # 删除 error.log 文件
        # rm -f Kelee-Loon/Plugin/error.log || echo "No error log to delete"

      
    - name: 提取链接
      if: env.LOON_SWITCH == 'true'
      run: |
        # 确保目标目录存在
        mkdir -p ../Script
    
        # 切换到 Plugin 目录
        cd Kelee-Loon/Plugin
    
        # 遍历 .plugin 文件并提取 .js 链接
        for file in *.plugin; do
          if [ -f "$file" ]; then
            # 提取链接
            grep -o 'https://kelee\.one/Resource/Script/[^ ]*\.js' "$file" | while read -r script_url; do
              script_name=$(basename "$script_url")
    
              # 确保下载目录存在
              if [ ! -d "../Script" ]; then
                echo "目标目录不存在，创建目录..."
                mkdir -p ../Script
              fi

              # 使用 curl 下载脚本
              curl -A "Surge iOS/3367" -L -o "../Script/$script_name" "$script_url" || echo "Failed to download $script_url" >> error.log
            done
          fi
        done


###### Commit
    - name: 添加Commits
      run: |
        cd Kelee-Loon
        if [[ -n $(git status -s) ]]; then
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Kelee-Loon Update $(TZ='Asia/Shanghai' date +'%Y-%m-%d %H:%M')"
          git push origin HEAD
        else
          echo "No changes to commit."
        fi
